#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2.5
bspc config window_gap           3
bspc config top_padding          25

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer false

bspc rule -a Pavucontrol state=floating
bspc rule -a kitty state=floating
bspc rule -a Galculator state=floating

# Border
bspc config focused_border_color        "#ffc52a"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"

# Autostart
picom -CGb &
/usr/bin/dunst &
$HOME/.config/polybar/bspwm.sh &
$HOME/.config/conky/launch.sh &
~/.config/bspwm/scripts/low_bat_notifier.sh
nm-applet --indicator &
nitrogen --random --set-zoom-fill /home/omk/Pictures/WP &
mpd &
libinput-gestures-setup start &
blueman-applet &
sleep 3 && insync start &

# disable DPMS screen blanking
sleep 10
xset s off -dpms &
xset s noblank &
