#!/bin/bash
#  ____ _____
# |  _ \_   _|  Derek Taylor (DistroTube)
# | | | || |    http://www.youtube.com/c/DistroTube
# | |_| || |    http://www.gitlab.com/dwt1/
# |____/ |_|
#
# Dmenu script for editing some of my more frequently edited config files.


declare -a options=("alacritty"
"sway"
"waybar"
"aliases"
"bspwm"
"neovim"
"polybar"
"polybar-mod"
"sxhkd"
"quit"
)

# The combination of echo and printf is done to add line breaks to the end of each
# item in the array before it is piped into dmenu.  Otherwise, all the items are listed
# as one long line (one item).

choice=$(echo "$(printf '%s\n' "${options[@]}")" | dmenu -p 'Edit config file: ')
case "$choice" in
	quit)
		echo "Program terminated." && exit 1
	;;
	alacritty)
		choice="$HOME/.config/alacritty/alacritty.yml"
	;;
    sway)
        choice="$HOME/.config/sway/config"
    ;;
    waybar)
        choice="$HOME/.config/waybar/config"
    ;;
    aliases)
        choice="$HOME/.aliases"
    ;;
	bspwm)
		choice="$HOME/.config/bspwm/bspwmrc"
	;;
	neovim)
		choice="$HOME/.config/nvim/init.vim"
	;;
	polybar)
		choice="$HOME/.config/polybar/config.ini"
    ;;
    polybar-mod)
        choice="$HOME/.config/polybar/modules.ini"
	;;
	sxhkd)
		choice="$HOME/.config/sxhkd/sxhkdrc"
	;;
	*)
		exit 1
	;;
esac

# Ultimately, what do want to do with our choice?  Open in our editor!
alacritty -e nvim "$choice"
